# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lwf\Desktop\seclass\firsttry.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!
from calculate import get_formula
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(785, 645)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setEnabled(True)
        self.gridWidget.setGeometry(QtCore.QRect(20, 170, 701, 431))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_3 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout.addWidget(self.textEdit_3, 0, 5, 1, 1)
        self.la_18 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_18.setFont(font)
        self.la_18.setText("")
        self.la_18.setAlignment(QtCore.Qt.AlignCenter)
        self.la_18.setObjectName("la_18")
        self.gridLayout.addWidget(self.la_18, 7, 7, 1, 1)
        self.la_19 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_19.setFont(font)
        self.la_19.setText("")
        self.la_19.setAlignment(QtCore.Qt.AlignCenter)
        self.la_19.setObjectName("la_19")
        self.gridLayout.addWidget(self.la_19, 8, 7, 1, 1)
        self.la_4 = QtWidgets.QLabel(self.gridWidget)
        self.la_4.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_4.setFont(font)
        self.la_4.setText("")
        self.la_4.setObjectName("la_4")
        self.gridLayout.addWidget(self.la_4, 8, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 10, 5, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout.addWidget(self.textEdit_4, 0, 8, 1, 1)
        self.textEdit_5 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout.addWidget(self.textEdit_5, 0, 12, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 10, 8, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 10, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 10, 12, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridWidget)
        self.label_18.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 8, 10, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridWidget)
        self.label_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 10, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridWidget)
        self.label_25.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 9, 10, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridWidget)
        self.label_10.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 10, 1, 1)
        self.la_11 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_11.setFont(font)
        self.la_11.setText("")
        self.la_11.setAlignment(QtCore.Qt.AlignCenter)
        self.la_11.setObjectName("la_11")
        self.gridLayout.addWidget(self.la_11, 0, 2, 1, 2)
        self.la_13 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_13.setFont(font)
        self.la_13.setText("")
        self.la_13.setAlignment(QtCore.Qt.AlignCenter)
        self.la_13.setObjectName("la_13")
        self.gridLayout.addWidget(self.la_13, 7, 2, 1, 2)
        self.la_14 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_14.setFont(font)
        self.la_14.setText("")
        self.la_14.setAlignment(QtCore.Qt.AlignCenter)
        self.la_14.setObjectName("la_14")
        self.gridLayout.addWidget(self.la_14, 8, 2, 1, 2)
        self.textEdit_13 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_13.setFont(font)
        self.textEdit_13.setReadOnly(True)
        self.textEdit_13.setObjectName("textEdit_13")
        self.gridLayout.addWidget(self.textEdit_13, 9, 5, 1, 1)
        self.la_20 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_20.setFont(font)
        self.la_20.setText("")
        self.la_20.setAlignment(QtCore.Qt.AlignCenter)
        self.la_20.setObjectName("la_20")
        self.gridLayout.addWidget(self.la_20, 9, 7, 1, 1)
        self.la_7 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_7.setFont(font)
        self.la_7.setText("")
        self.la_7.setObjectName("la_7")
        self.gridLayout.addWidget(self.la_7, 5, 6, 1, 1)
        self.la_10 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_10.setFont(font)
        self.la_10.setText("")
        self.la_10.setObjectName("la_10")
        self.gridLayout.addWidget(self.la_10, 9, 6, 1, 1)
        self.la_6 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_6.setFont(font)
        self.la_6.setText("")
        self.la_6.setObjectName("la_6")
        self.gridLayout.addWidget(self.la_6, 0, 6, 1, 1)
        self.textEdit_8 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_8.setFont(font)
        self.textEdit_8.setReadOnly(True)
        self.textEdit_8.setObjectName("textEdit_8")
        self.gridLayout.addWidget(self.textEdit_8, 5, 5, 1, 1)
        self.textEdit_14 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_14.setFont(font)
        self.textEdit_14.setReadOnly(True)
        self.textEdit_14.setObjectName("textEdit_14")
        self.gridLayout.addWidget(self.textEdit_14, 8, 5, 1, 1)
        self.la_9 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_9.setFont(font)
        self.la_9.setText("")
        self.la_9.setObjectName("la_9")
        self.gridLayout.addWidget(self.la_9, 8, 6, 1, 1)
        self.la_15 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_15.setFont(font)
        self.la_15.setText("")
        self.la_15.setAlignment(QtCore.Qt.AlignCenter)
        self.la_15.setObjectName("la_15")
        self.gridLayout.addWidget(self.la_15, 9, 2, 1, 2)
        self.la_12 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_12.setFont(font)
        self.la_12.setText("")
        self.la_12.setAlignment(QtCore.Qt.AlignCenter)
        self.la_12.setObjectName("la_12")
        self.gridLayout.addWidget(self.la_12, 5, 2, 1, 2)
        self.textEdit_12 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_12.setFont(font)
        self.textEdit_12.setReadOnly(True)
        self.textEdit_12.setObjectName("textEdit_12")
        self.gridLayout.addWidget(self.textEdit_12, 9, 1, 1, 1)
        self.la_8 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_8.setFont(font)
        self.la_8.setText("")
        self.la_8.setObjectName("la_8")
        self.gridLayout.addWidget(self.la_8, 7, 6, 1, 1)
        self.textEdit_17 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_17.setFont(font)
        self.textEdit_17.setReadOnly(True)
        self.textEdit_17.setObjectName("textEdit_17")
        self.gridLayout.addWidget(self.textEdit_17, 8, 8, 1, 1)
        self.textEdit_18 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_18.setFont(font)
        self.textEdit_18.setReadOnly(True)
        self.textEdit_18.setObjectName("textEdit_18")
        self.gridLayout.addWidget(self.textEdit_18, 9, 8, 1, 1)
        self.textEdit_15 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_15.setFont(font)
        self.textEdit_15.setReadOnly(True)
        self.textEdit_15.setObjectName("textEdit_15")
        self.gridLayout.addWidget(self.textEdit_15, 7, 5, 1, 1)
        self.textEdit_19 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_19.setFont(font)
        self.textEdit_19.setObjectName("textEdit_19")
        self.gridLayout.addWidget(self.textEdit_19, 9, 12, 1, 1)
        self.textEdit_6 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_6.setFont(font)
        self.textEdit_6.setObjectName("textEdit_6")
        self.gridLayout.addWidget(self.textEdit_6, 5, 12, 1, 1)
        self.textEdit_21 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_21.setFont(font)
        self.textEdit_21.setObjectName("textEdit_21")
        self.gridLayout.addWidget(self.textEdit_21, 7, 12, 1, 1)
        self.textEdit_20 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_20.setFont(font)
        self.textEdit_20.setObjectName("textEdit_20")
        self.gridLayout.addWidget(self.textEdit_20, 8, 12, 1, 1)
        self.textEdit_16 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_16.setFont(font)
        self.textEdit_16.setReadOnly(True)
        self.textEdit_16.setObjectName("textEdit_16")
        self.gridLayout.addWidget(self.textEdit_16, 7, 8, 1, 1)
        self.la_1 = QtWidgets.QLabel(self.gridWidget)
        self.la_1.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_1.setFont(font)
        self.la_1.setText("")
        self.la_1.setObjectName("la_1")
        self.gridLayout.addWidget(self.la_1, 0, 0, 1, 1)
        self.la_2 = QtWidgets.QLabel(self.gridWidget)
        self.la_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_2.setFont(font)
        self.la_2.setText("")
        self.la_2.setObjectName("la_2")
        self.gridLayout.addWidget(self.la_2, 5, 0, 1, 1)
        self.textEdit_7 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_7.setFont(font)
        self.textEdit_7.setReadOnly(True)
        self.textEdit_7.setObjectName("textEdit_7")
        self.gridLayout.addWidget(self.textEdit_7, 5, 8, 1, 1)
        self.la_16 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_16.setFont(font)
        self.la_16.setText("")
        self.la_16.setAlignment(QtCore.Qt.AlignCenter)
        self.la_16.setObjectName("la_16")
        self.gridLayout.addWidget(self.la_16, 0, 7, 1, 1)
        self.textEdit_9 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_9.setFont(font)
        self.textEdit_9.setReadOnly(True)
        self.textEdit_9.setObjectName("textEdit_9")
        self.gridLayout.addWidget(self.textEdit_9, 5, 1, 1, 1)
        self.la_17 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_17.setFont(font)
        self.la_17.setText("")
        self.la_17.setAlignment(QtCore.Qt.AlignCenter)
        self.la_17.setObjectName("la_17")
        self.gridLayout.addWidget(self.la_17, 5, 7, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridWidget)
        self.label_15.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(39)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 10, 1, 1)
        self.textEdit_11 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_11.setFont(font)
        self.textEdit_11.setReadOnly(True)
        self.textEdit_11.setObjectName("textEdit_11")
        self.gridLayout.addWidget(self.textEdit_11, 8, 1, 1, 1)
        self.la_3 = QtWidgets.QLabel(self.gridWidget)
        self.la_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_3.setFont(font)
        self.la_3.setText("")
        self.la_3.setObjectName("la_3")
        self.gridLayout.addWidget(self.la_3, 7, 0, 1, 1)
        self.la_5 = QtWidgets.QLabel(self.gridWidget)
        self.la_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.la_5.setFont(font)
        self.la_5.setText("")
        self.la_5.setObjectName("la_5")
        self.gridLayout.addWidget(self.la_5, 9, 0, 1, 1)
        self.textEdit_10 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_10.setFont(font)
        self.textEdit_10.setReadOnly(True)
        self.textEdit_10.setObjectName("textEdit_10")
        self.gridLayout.addWidget(self.textEdit_10, 7, 1, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 884, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 100, 445, 70))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(500, 120, 81, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 20))
        self.menubar.setObjectName("menubar")
        self.pushButton_4.setEnabled(False)
        self.pushButton.setEnabled(False)
        self.pushButton_3.setEnabled(False)
        self.pushButton_2.setEnabled(False)
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.pushButton_5.clicked.connect(self.get_problems)
        self.pushButton.clicked.connect(self.get_view_answer)
        self.pushButton_3.clicked.connect(self.get_next_page)
        self.pushButton_4.clicked.connect(self.get_last_page)
        self.pushButton_2.clicked.connect(self.check_rst)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Next Page"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "View Answers"))
        self.pushButton_4.setText(_translate("MainWindow", "Last Page"))
        self.pushButton_2.setText(_translate("MainWindow", "Check Results"))
        self.label_18.setText(_translate("MainWindow", "="))
        self.label_5.setText(_translate("MainWindow", "="))
        self.label_25.setText(_translate("MainWindow", "="))
        self.label_10.setText(_translate("MainWindow", "="))
        self.textEdit_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_14.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_18.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_19.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "="))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Simple UI on my first try"))
        self.label_2.setText(_translate("MainWindow", "Input the number of exercise problems:"))
        self.pushButton_5.setText(_translate("MainWindow", "Commit"))

    def get_problems(self):
        n = self.lineEdit.text()
        if not n.isdigit() or type(eval(n)) == float or int(n) > 1000 or int(n) <= 0:
            reply = QMessageBox.warning(self.pushButton_5, 'Warning', 'Please input a positive integer and 0<n<=1000.', \
                                        QMessageBox.Yes)
            self.lineEdit.clear()
        else:
            self.n = n = int(n)
            lst = get_formula(n)
            self.lst = lst
            self.cnt = 0
            self.check_if_next()
            self.check_if_last()
            self.clear_eq()
            self.pushButton_2.setEnabled(True)
            self.pushButton.setEnabled(True)
            self.show_eq()

    def show_eq(self):
        cnt = self.cnt
        if cnt < self.n:
            if self.lst[cnt][-2] is True:
                self.la_1.setText('(')
                self.la_6.setText(')')
            self.textEdit_2.setPlainText(self.lst[cnt][0])
            self.textEdit_3.setPlainText(self.lst[cnt][1])
            self.textEdit_4.setPlainText(self.lst[cnt][2])
            self.la_11.setText(self.lst[cnt][3])
            self.la_16.setText(self.lst[cnt][4])

        cnt += 1
        if cnt < self.n:
            if self.lst[cnt][-2] is True:
                self.la_2.setText('(')
                self.la_7.setText(')')
            self.textEdit_9.setPlainText(self.lst[cnt][0])
            self.textEdit_8.setPlainText(self.lst[cnt][1])
            self.textEdit_7.setPlainText(self.lst[cnt][2])
            self.la_12.setText(self.lst[cnt][3])
            self.la_17.setText(self.lst[cnt][4])

        cnt += 1
        if cnt< self.n:
            if self.lst[cnt][-2] is True:
                self.la_3.setText('(')
                self.la_8.setText(')')
            self.textEdit_10.setPlainText(self.lst[cnt][0])
            self.textEdit_15.setPlainText(self.lst[cnt][1])
            self.textEdit_16.setPlainText(self.lst[cnt][2])
            self.la_13.setText(self.lst[cnt][3])
            self.la_18.setText(self.lst[cnt][4])

        cnt += 1
        if cnt < self.n:
            if self.lst[cnt][-2] is True:
                self.la_4.setText('(')
                self.la_9.setText(')')
            self.textEdit_11.setPlainText(self.lst[cnt][0])
            self.textEdit_14.setPlainText(self.lst[cnt][1])
            self.textEdit_17.setPlainText(self.lst[cnt][2])
            self.la_14.setText(self.lst[cnt][3])
            self.la_19.setText(self.lst[cnt][4])

        cnt += 1
        if cnt < self.n:
            if self.lst[cnt][-2] is True:
                self.la_5.setText('(')
                self.la_10.setText(')')
            self.textEdit_12.setPlainText(self.lst[cnt][0])
            self.textEdit_13.setPlainText(self.lst[cnt][1])
            self.textEdit_18.setPlainText(self.lst[cnt][2])
            self.la_15.setText(self.lst[cnt][3])
            self.la_20.setText(self.lst[cnt][4])

    def check_rst(self):
        val_1 = self.textEdit_5.toPlainText()
        val_2 = self.textEdit_6.toPlainText()
        val_3 = self.textEdit_21.toPlainText()
        val_4 = self.textEdit_20.toPlainText()
        val_5 = self.textEdit_19.toPlainText()

        if val_1 == self.lst[self.cnt][-1]:
            self.textEdit_5.setStyleSheet('''color:rgb(0,255,0)''')
        elif val_1 == "":
            pass
        else:
            self.textEdit_5.setStyleSheet('''color:rgb(255,0,0)''')
        if self.cnt+1 < self.n:
            if val_2 == self.lst[self.cnt+1][-1]:
                self.textEdit_6.setStyleSheet('''color:rgb(0,255,0)''')
            elif val_2 == "":
                pass
            else:
                self.textEdit_6.setStyleSheet('''color:rgb(255,0,0)''')
        if self.cnt+2 < self.n:
            if val_3 == self.lst[self.cnt+2][-1]:
                self.textEdit_21.setStyleSheet('''color:rgb(0,255,0)''')
            elif val_3 == "":
                pass
            else:
                self.textEdit_21.setStyleSheet('''color:rgb(255,0,0)''')
        if self.cnt+3 < self.n:
            if val_4 == self.lst[self.cnt+3][-1]:
                self.textEdit_20.setStyleSheet('''color:rgb(0,255,0)''')
            elif val_4 == "":
                pass
            else:
                self.textEdit_20.setStyleSheet('''color:rgb(255,0,0)''')
        if self.cnt+4 < self.n:
            if val_5 == self.lst[self.cnt+4][-1]:
                self.textEdit_19.setStyleSheet('''color:rgb(0,255,0)''')
            elif val_5 == "":
                pass
            else:
                self.textEdit_19.setStyleSheet('''color:rgb(255,0,0)''')


    def get_view_answer(self):
        self.set_text_color_default()
        self.textEdit_5.setPlainText(self.lst[self.cnt][-1])
        if self.cnt+1 < self.n:
            self.textEdit_6.setPlainText(self.lst[self.cnt+1][-1])
        if self.cnt + 2 < self.n:
            self.textEdit_21.setPlainText(self.lst[self.cnt+2][-1])
        if self.cnt + 3 < self.n:
            self.textEdit_20.setPlainText(self.lst[self.cnt+3][-1])
        if self.cnt + 4 < self.n:
            self.textEdit_19.setPlainText(self.lst[self.cnt+4][-1])

    def get_next_page(self):
        self.cnt += 5
        self.clear_eq()
        self.show_eq()
        self.check_if_next()
        self.check_if_last()

    def get_last_page(self):
        self.cnt -= 5
        self.clear_eq()
        self.show_eq()
        self.check_if_next()
        self.check_if_last()

    def check_if_next(self):
        if self.cnt + 5 >= self.n:
            self.pushButton_3.setEnabled(False)
        else:
            self.pushButton_3.setEnabled(True)

    def check_if_last(self):
        if self.cnt >= 5:
            self.pushButton_4.setEnabled(True)
        else:
            self.pushButton_4.setEnabled(False)

    def clear_eq(self):
        self.la_5.clear()
        self.la_10.clear()
        self.textEdit_12.clear()
        self.textEdit_13.clear()
        self.textEdit_18.clear()
        self.la_15.clear()
        self.la_20.clear()

        self.la_4.clear()
        self.la_9.clear()
        self.textEdit_11.clear()
        self.textEdit_14.clear()
        self.textEdit_17.clear()
        self.la_14.clear()
        self.la_19.clear()

        self.la_3.clear()
        self.la_8.clear()
        self.textEdit_10.clear()
        self.textEdit_15.clear()
        self.textEdit_16.clear()
        self.la_13.clear()
        self.la_18.clear()

        self.la_2.clear()
        self.la_7.clear()
        self.textEdit_9.clear()
        self.textEdit_8.clear()
        self.textEdit_7.clear()
        self.la_12.clear()
        self.la_17.clear()

        self.la_1.clear()
        self.la_6.clear()
        self.textEdit_2.clear()
        self.textEdit_3.clear()
        self.textEdit_4.clear()
        self.la_11.clear()
        self.la_16.clear()

        self.textEdit_5.clear()
        self.textEdit_6.clear()
        self.textEdit_19.clear()
        self.textEdit_20.clear()
        self.textEdit_21.clear()
        self.set_text_color_default()

    def set_text_color_default(self):
        self.textEdit_5.setStyleSheet('''color:rgb(0,0,0)''')
        self.textEdit_6.setStyleSheet('''color:rgb(0,0,0)''')
        self.textEdit_19.setStyleSheet('''color:rgb(0,0,0)''')
        self.textEdit_20.setStyleSheet('''color:rgb(0,0,0)''')
        self.textEdit_21.setStyleSheet('''color:rgb(0,0,0)''')